stages:
  - test

test-python27:
  image: python:2.7-alpine # python image comes with pip
  stage: test
  script:
    - pip install -r requirements_dev.txt
    - python -m pytest -v tests/unit/*.py

test-python36:
  image: python:3.6-alpine # python image comes with pip
  stage: test
  script:
    - pip install -r requirements_dev.txt
    - python -m pytest -v tests/unit/*.py